spring.application.name=ScreenSound
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.url=jdbc:postgresql//${DB_HOST}:5432/${DB_SOUND}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
openai.ai.key=${OPENAI_API_KEY}